version: '3'
services:
  database:
    container_name: database
    image: mariadb:latest
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    restart: on-failure
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_USER_PW}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
      MYSQL_USER: ${DB_USER}
  
  api-server:
    build: ./api-server/
    container_name: api-server
    ports: 
      - "${API_SERVER_PORT}:${API_SERVER_PORT}"
    depends_on: 
      - database
    restart: on-failure
  
  game-server:
    build: ./game-server/
    container_name: game-server
    ports: 
      - "${GAME_SERVER_PORT}:${GAME_SERVER_PORT}"
    depends_on: 
      - api-server
    restart: on-failure

networks:
  default:
volumes:
  data:
    driver: local
